application:
  max-allowed-books: 2
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
server:
  port:8084
management:
  endpoint:
    env:
      show-values: always
    metrics:
      enabled: true

  endpoints:
    web:
      exposure:
        include: env,prometheus,health,ingo,metrics